### ISSUE TITLE
Dertermine and setup a persistence layer.

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#10]
We need some form of a persistence layer.

- We could use firebase's firestore and get the added bonus of idiot-proof authentication and noSQL, but we cannot store ~~GIS~~ complex GIS data. (something I don't think we actually need for milestone 1)

- The other option is to just use a SQL database that is always accessed through our own backend. This has the bonus of easy GIS storage and [great support](https://osm2pgsql.org/) for gathering OSM data at the drawback of needing the backend and frontend to communicate changes better. This would be overengineering it for milestone 1. Note we can also access firestore data from kotlin.

- We could also do a combination of these two, ie. restrict the backend to *only* handling GIS-related data. This would free the frontend to belligerently change how they do persistence for more user-facing changes (faster development), while also keeping the benefits of SQL where it is needed.  I think the drawback of this is splitting where we store data. This could prevent some fancier logic that would necessitate getting data from both sources. ie. have a "common routes" attached to a user via firestore, but we need GIS attached to that that so we also need to hit the SQL server in order to display it. 

I would vote for solution 1, incrementally moving towards 3 as it becomes needed.

Note if we go the firebase route, we also have to decide between [firestore and realtime-db](https://firebase.google.com/docs/database/rtdb-vs-firestore?authuser=0)

**Comment by doug-stormtree** [comment]
Good writeup. Per the meeting last Thursday we likely only need something as simple as decimal lat/long and the [Geohash](https://firebase.google.com/docs/firestore/solutions/geoqueries) solution that Firebase proposes if we only have fuzzy start and end route points to store.

Solution one with realtime-db will be adopted for milestone1.
