### ISSUE TITLE
User can be driver and passenger in same ride

### ISSUE THREAD

**Issue by doug-stormtree** [CobeyH/SENG-480A#102]
**Describe the bug**
User shouldn't be allowed to be both the Driver and Passenger for the same ride.

**To Reproduce**
1. Go to any Ride
2. Click on Join next to both Driver and Passengers

**Expected behavior**
Driver and Passenger are mutually exclusive

**Comment by CobeyH** [comment]
This may also be a minor UX issue. The interface doesn't make it clear that the driver and passengers fields are separate. I thought the expected behaviour was the ride to start with 1/4 if you created it as a driver.

**Comment by CobeyH** [comment]
I fixed this in PR #88
