### ISSUE TITLE
Map Routing

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#147]
* Feature name: Map Routing
* Description: Determine which API to use for map directions. This is probably needed to create the entire user experience such as determining pickup order.
* Requires: We will probably need to decide this as a group.
* Status: Open Directions API selected. Implementation started.
* Time Estimation: 2 hours.

**Comment by CobeyH** [comment]
So for Routing I’d suggest we use either MapQuest’s API ( https://developer.mapquest.com/documentation/mapquest-js/v1.3/) which gives us 15,000 free queries a month or we could use the Leaflet Routing Machine (https://www.liedman.net/leaflet-routing-machine/) which requires us to host our own backend for doing the routing computation.

**Comment by CobeyH** [comment]
It looks like Leaflet Routing Machine isn't maintained anymore. We may want to use MapQuest instead of find something else.

**Comment by doug-stormtree** [comment]
For reference, Google is [pay-as-you-go](https://developers.google.com/maps/documentation/directions/usage-and-billing) but offers:
- $200 per month of free credits,
- $0.005 per request to Directions or Distance (time estimates),
- $0.01 per request that includes traffic live data or estimations,

Which is between 20,000 and 40,000 free requests per month.

**Comment by CobeyH** [comment]
We have decided to use Open Directions API for this project.
