### ISSUE TITLE
Determine library for interactive maps.

### ISSUE THREAD

**Issue by doug-stormtree** [CobeyH/SENG-480A#15]
We will need a library for building a frontend component with interactive maps, including the ability to get point positions for creating routes.
- [LeafletJS](https://leafletjs.com) has been proposed.

**Comment by MarcusDunn** [comment]
[embedding google maps](https://developers.google.com/maps/documentation/embed/get-started) is also an option

**Comment by doug-stormtree** [comment]
I did some quick research and I like the look of [Pigeon Maps](https://pigeon-maps.js.org) and there exists [React Leaflet](https://react-leaflet.js.org), the latter seems more mature.

If we want to display routes it may be in our best interests to start with Google Maps, but I worry about the complexity.

**Comment by doug-stormtree** [comment]
Going to close this with Leaflet and React Leaflet based on their ease to implement now that I've read the docs.
