### ISSUE TITLE
Add Vehicles to User Account

### ISSUE THREAD

**Issue by doug-stormtree** [CobeyH/SENG-480A#153]
* Feature name: Vehicles in User Accounts
* Description: Each user should be able to add vehicles to their account, with an associated fuel efficiency and passenger capacity.
* Requires: N/A
* Status: Open
* Time Estimation: 3 hours

**Comment by CobeyH** [comment]
I am using this gas consumption guide for reference: https://www.nrcan.gc.ca/sites/nrcan/files/oee/pdf/transportation/tools/fuelratings/2021%20Fuel%20Consumption%20Guide.pdf
