### ISSUE TITLE
Routing Points/ Detours

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#166]
* Feature name: Detours
* Description: Allow riders to make detours to the ride. This serves for both pickups as well as coffee runs.
* Requires:
* Status: Implementation started.
* Time Estimation: A fairly large PR. 2-3 hours of actual work. Hopefully, completed by the 7th

**Additional context**
 - For now let anyone create a detour as long as they in the ride
 - This should update the ride preview

**Comment by doug-stormtree** [comment]
<img width="1045" alt="Screen Shot 2022-03-06 at 4 04 23 PM" src="https://user-images.githubusercontent.com/43759986/156948224-625ec748-0df0-4a86-9d5b-37328761f8e8.png">

**Comment by CobeyH** [comment]
Nice flowchart! I think the only thing this doesn't encapsulate is the passenger's ability to either create a new pickup point or join one that already exists.
