### ISSUE TITLE
Determine if we want simple checks for frontend

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#17]
do we want a very simple action that runs `tsc --no-emit` to type check everything? I imagine the preview would definitely show *something* was wrong, but may be helpful to prevent clearly broken PR's. I highly doubt we'll be doing much testing so this seems a happy medium

**Comment by doug-stormtree** [comment]
I don't have any experience with frontend testing but I was thinking about it. This does seem like a good idea.
