### ISSUE TITLE
Number of members are out of nothing in public groups search

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#207]
**Describe the bug**
See screenshot, number of members are out of nothing.

**To Reproduce**
Search for public groups

**Expected behaviour**
The number of members to be actually "out of" something

**Screenshots**

![image](https://user-images.githubusercontent.com/51931484/157796653-e0404a7f-15fa-4a45-8546-548ab14f809d.png)

**Comment by CobeyH** [comment]
This is simply a backwards compatibility issue. It only happens on groups that were created before this feature was added. I think It may be time to wipe the database since a lot of the old groups are missing critical data and don't load anyways.

**Comment by CobeyH** [comment]
We have wiped the database. This isn't an issue anymore.
