### ISSUE TITLE
Blank screen when trying to join public group

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#208]
**Describe the bug**
Joining a public group gives a white page
With errors `u.pickupPoints is undefined`

**To Reproduce**
Search a public group in the groups list page
Join one.
Watch the screen turn white.

**Expected behavior**
A non-white screen

**Screenshots**
![image](https://user-images.githubusercontent.com/51931484/157796982-455fc34d-4b04-47d0-af0f-9477f103f364.png)

**Comment by CobeyH** [comment]
I think it's another error to do with old rides without the correct data in them. We should probably provide better safety but this shouldn't happen in general.

**Comment by MarcusDunn** [comment]
calling this resolved after database wipe. Cannot reproduce.

**Comment by CobeyH** [comment]
![image](https://user-images.githubusercontent.com/32989729/158040280-011ea3f2-56e7-4cc8-9c7c-8c463c192f82.png)
I just tried and I got this error. Did you upload a banner and a profile picture?
