### ISSUE TITLE
Add context to share group message

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#212]
Give the user some direction on the strange URL we just presented them with.

**Comment by CobeyH** [comment]
We need to decide what we want the context message to say when you generate a share-link. Maybe you could comment a suggestion @samanthamhill ?

**Comment by samanthamhill** [comment]
(user name) invited you to join their carpooling group! Follow the link to join the group. (Link) You may need to create an account. 

And if we can include a tiny version of the logo on it that would be awesome.
