### ISSUE TITLE
Facebook registration handling already used email error

### ISSUE THREAD

**Issue by samanthamhill** [CobeyH/SENG-480A#276]
**Describe the bug**
When registering with facebook, if the user has already made an account with the email they use for facebook a silent error is thrown

**To Reproduce**
Log in with facebook that has same email as another account

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by CobeyH** [comment]
I don't have a way to test this. The error doesn't occur when using the authentication emulators and I don't have a facebook account registered with a gmail account to test it for real.

**Comment by samanthamhill** [comment]
![Screen Shot 2022-03-22 at 12 33 53 PM](https://user-images.githubusercontent.com/74685702/159561265-dd829fe3-b42a-47df-b509-e9b1a2d87502.png)
