### ISSUE TITLE
Icon sizes are too big on Safari

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#281]
**Describe the bug**
When creating a group on Safari, the icon profile pictures aren't the correct size.

**To Reproduce**
1. Open the app on Safari
2. Create a new group
3. View the "Icon Profile Pictures"

**Expected behavior**
The icons will look the same on Safari and Chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/32989729/158911293-f180d9b3-9960-46df-b896-041926da10b1.png)

**Comment by samanthamhill** [comment]
This is also the case on chrome on mobile.

**Comment by CobeyH** [comment]
When I try to load the app on Safari on my Mac I see this 
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/32989729/159102970-58972bf9-b9c0-433d-9136-210392a23910.png">
