### ISSUE TITLE
User onboarding 

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#288]
I've found a common theme when I just drop a friend into the app is they don't know *what to do* after signing up. Some form of onboarding or visual indications on first login could be a solution.

**Comment by CobeyH** [comment]
I agree. This is kind of what I was talking about as a tutorial yesterday. I think just a little popup pointing to the "Create Group" or "Join Group" would be good to explain to users that they need to be in a group to see rides.

**Comment by CobeyH** [comment]
It sounds like this is the most popular onboarding package: https://github.com/gilbarbara/react-joyride

**Comment by CobeyH** [comment]
This is helpful: https://www.appcues.com/blog/product-tours-walkthroughs-ultimate-guide

**Comment by CobeyH** [comment]
The functionality is there and easy to extend. We mainly need to style this to make it look nice.

**Comment by CobeyH** [comment]
Blocked waiting for styling suggestions from team.
