### ISSUE TITLE
Create Standardized Code Formatting

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#30]
We need to set up a formatter so that we aren't switching back and forth between everybody's individual format. It's creating huge diffs in the pull requests which makes it difficult to see what was actually changed.

**Comment by doug-stormtree** [comment]
I fully support this, if you want to commit your Prettier config since I think you said you had one setup that would be great and we can tweak if necessary.

Should we add this to a Github Action for each commit or keep it local for everyone?

**Comment by CobeyH** [comment]
Okay so the formatting conclusion is thus: Prettier provides formatting but doesn't do any linting (such as unused variables). ESLint provides both formatting and linting but it isn't nearly as good at formatting as Prettier. So I'm going to add both of these to our project and disable the code formatting components of ESLint so that Prettier can do that. However, I think this doesn't prevent IDEs from trying to break the formatting when files are saved. So I can use EditorConfig to change the default formatting options for different IDEs. This won't matter for all the VSCode users that have the prettier extension since that formats identically to the command line prettier, but it will hopefully help Marcus when he is using Intelij

**Comment by MarcusDunn** [comment]
resolved by https://github.com/CobeyH/SENG-480A/pull/35
