### ISSUE TITLE
Registration and Login page toast causes container size to change

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#317]
The width of the part of the registration page changes when there is an error. Becoming thinner. The same issue occurs in login page.
![image](https://user-images.githubusercontent.com/51931484/159780837-ae30c4bf-e8bd-4b0b-82f8-87d266df7510.png)

**Comment by samanthamhill** [comment]
Can we add an exit button the the toasts as well, it's annoying to not be able to get rid of them.
