### ISSUE TITLE
Improved breadcrumbs

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#321]
A complaint among users were the breadcrumbs were not obvious in their purpose. We should style them better in order to convey that that *they take you places*.

Some ideas:

https://catalin.red/css3-breadcrumbs/

**Comment by CobeyH** [comment]
Is this still needed? I think our app is now only two pages deep at it's deepest point. Unless we are going to make more levels, I think we should just have a "back" button instead of breadcrumbs. @MarcusDunn

**Comment by MarcusDunn** [comment]
I'd vote not needed. If we manage to keep the UI in a place where a user doesn't need breadcrumbs that's great
