### ISSUE TITLE
Report a bug feature

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#334]
* Feature name: Report a bug feature
* Description: Allow public beta users to report bugs to us easily without requiring them to fill out a bug report on Github.
* Status: Not started
* Time Estimation: 2 hours.

**Additional context**
We need to decide on the complexity of this feature. Should it just be an email address link to our support email? Should we have a custom form that automatically generates a github issue? Do we want to store their responses in the database as raw JSON?

**Comment by CobeyH** [comment]
We could submit to google forms but that may be tricky to upload pictures. We could also use this: https://www.userbugreport.com/docs/

**Comment by CobeyH** [comment]
The user bug report integration seems pretty broken. It seems to require material UI as a dependency.

**Comment by jpark052** [comment]
> The user bug report integration seems pretty broken. It seems to require material UI as a dependency.

@CobeyH In that case, maybe we can just make it as an email link for now? We can just create an account for that purpose
