### ISSUE TITLE
Video Demo

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#438]
* Feature name: Demo Video
* Description: In your GitHub readme, post a link to a 5 minute video demonstrating the application
* Status: 

- [x] Try to show all the main features of your application and explain them in the video using your scenarios and personas.

- [x] Create a cover page in your video to show the course info, all team members, project name, tagline, and link to your GitHub and/or product page

* Time Estimation: 2 hours

**Comment by MarcusDunn** [comment]
https://www.youtube.com/watch?v=tKx8-qhpNMk
