### ISSUE TITLE
Test Creating group wizard

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#454]
Test creating groups, banner selections, keyboard shortcuts, what happens when a field is not filled.

**Comment by CobeyH** [comment]
I'm not sure how uploading file media will work in the automated testing. How will the github action get the image to upload as a banner?

**Comment by MarcusDunn** [comment]
You could use the tandem images already checked into the repo.

**Comment by CobeyH** [comment]
I'm not sure if this is necessary but we could use this to handle file uploading: https://www.npmjs.com/package/cypress-file-upload

**Comment by CobeyH** [comment]
As of January, Cypress has replaced the previously mentioned file uploading plugin with this: https://www.cypress.io/blog/2022/01/19/uploading-files-with-selectfile/#header
