### ISSUE TITLE
Test ride cards

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#457]
this will be a fair bit, open them, close them, join them as driver and passenger, leave as driver and passenger, and add a pickup point.

**Comment by CobeyH** [comment]
- [ ] Open ride card
- [ ] Close ride card
- [ ] Join ride as driver
- [ ] Join ride as passenger
- [ ] Leave as driver
- [ ] Leave as passenger
- [ ] Add pickup point
- [ ] Show previous rides
- [ ] #88
