### ISSUE TITLE
Decide what details are needed for rides

### ISSUE THREAD

**Issue by doug-stormtree** [CobeyH/SENG-480A#55]
For Milestone 1, what details are needed for rides?

Long list to be narrowed down (or added to):
- Title
- Description
- Start/End location names? converted to street addresses?
- Number of seats
- Driver(s)
- Equipment (kayak/surfboard)
- Time and Dates

**Comment by MarcusDunn** [comment]
Decided in GC

 - Numbers of seat total / available 
 - Title
 - Start and End points (no address, just coords)
 - Description
 - Driver
