### ISSUE TITLE
Create Issue Template for bugs and featues

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#78]
Example as given in [milestone 1](https://github.com/margaretstorey/startup2022/blob/main/milestone%201%20-%20proof%20of%20concept.md )
> - Feature name: Where did you park your car?
> - Description: A Google map in which one could locate where he/she parks the family car.
> - Requires: Adding logic to the server, working with Google maps API, adding client side support.
> - Due: Milestone 2.
> - Status: Server side ready, other parts are missing.
> - Time Estimation: 12 hours.

**Comment by CobeyH** [comment]
Resolved in #80
